// <auto-generated />
using System;
using GeoMottuMinimalApi.Infrastructure.Data.AppDatas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace GeoMottuMinimalApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251104212702_addRoleProp")]
    partial class addRoleProp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeoMottuMinimalApi.Domain.Entities.FilialEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_FILIAL");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("ENDERECO_FILIAL");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ESTADO_FILIAL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NM_FILIAL");

                    b.Property<string>("PaisFilial")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PAIS_FILIAL");

                    b.HasKey("Id");

                    b.ToTable("TB_GEOMOTTU_FILIAL");
                });

            modelBuilder.Entity("GeoMottuMinimalApi.Domain.Entities.MotoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MOTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("NVARCHAR2(17)")
                        .HasColumnName("CHASSI_MOTO");

                    b.Property<string>("CodPlacaIot")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CD_IOT_PLACA");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MOTO_MODELO");

                    b.Property<double>("Motor")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("MOTOR_MOTO");

                    b.Property<int>("PatioId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Placa")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("PLACA_MOTO");

                    b.Property<double>("PosicaoX")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("PosicaoY")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("Proprietario")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("MOTO_PROPRIETARIO");

                    b.HasKey("Id");

                    b.HasIndex("Chassi")
                        .IsUnique();

                    b.HasIndex("CodPlacaIot")
                        .IsUnique()
                        .HasFilter("\"CD_IOT_PLACA\" IS NOT NULL");

                    b.HasIndex("PatioId");

                    b.HasIndex("Placa")
                        .IsUnique()
                        .HasFilter("\"PLACA_MOTO\" IS NOT NULL");

                    b.ToTable("TB_GEOMOTTU_MOTO");
                });

            modelBuilder.Entity("GeoMottuMinimalApi.Domain.Entities.PatioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PATIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacidadeTotal")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CAPC_PATIO");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("FilialId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("LocalizacaoReferencia")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("REFERENCIA_PATIO");

                    b.Property<double>("Tamanho")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("TAMANHO_PATIO");

                    b.Property<string>("TipoDoPatio")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("FilialId");

                    b.ToTable("TB_GEOMOTTU_PATIO");
                });

            modelBuilder.Entity("GeoMottuMinimalApi.Domain.Entities.UsuarioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CadastradoEm")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("EMAIL_FUNCIONARIO");

                    b.Property<int>("FilialId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME_USUARIO");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ROLE_FUNCIONARIO");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SENHA_FUNCIONARIO");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FilialId");

                    b.ToTable("TB_GEOMOTTU_USUARIO");
                });

            modelBuilder.Entity("GeoMottuMinimalApi.Domain.Entities.MotoEntity", b =>
                {
                    b.HasOne("GeoMottuMinimalApi.Domain.Entities.PatioEntity", "Patio")
                        .WithMany("Motos")
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("GeoMottuMinimalApi.Domain.Entities.PatioEntity", b =>
                {
                    b.HasOne("GeoMottuMinimalApi.Domain.Entities.FilialEntity", "Filial")
                        .WithMany("Patios")
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filial");
                });

            modelBuilder.Entity("GeoMottuMinimalApi.Domain.Entities.UsuarioEntity", b =>
                {
                    b.HasOne("GeoMottuMinimalApi.Domain.Entities.FilialEntity", "Filial")
                        .WithMany("Usuarios")
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filial");
                });

            modelBuilder.Entity("GeoMottuMinimalApi.Domain.Entities.FilialEntity", b =>
                {
                    b.Navigation("Patios");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("GeoMottuMinimalApi.Domain.Entities.PatioEntity", b =>
                {
                    b.Navigation("Motos");
                });
#pragma warning restore 612, 618
        }
    }
}
